### ISSUE TITLE
How to get the Luna16 datasets?

### ISSUE THREAD

**Issue by DaLei001** [GarkP/LUNA16_Challange#2]
I'm not join the LUNA16 challenge, Could I get the LUNA16 dataset and the tutorials? and how?
If you see this, tell me the answer please. Thank you!

**Comment by GorkemP** [comment]
Hi,
You can download the data freely. You just have to sign in to the https://luna16.grand-challenge.org.
Then in the download tab it redicrects you to the google drive, dropbox or academic torrents.
