### ISSUE TITLE
froc code 

### ISSUE THREAD

**Issue by vipparlavamsi** [GarkP/LUNA16_Challange#4]
dear sir,

Can you please upload/mail me the code for froc curve. I find your work very interesting and thank you for sharing this repository.
mail id: vipparla.vamsikrishna@gmail.com
thank you,

**Comment by GorkemP** [comment]
Hi,
you can download the script from the challenge web site. Here is the link:

https://luna16.grand-challenge.org/Download/

You need to download evaluation script.
